<!DOCTYPE html>
<html lang="en">
<head>
  <title>Martian Republic - Privacy Policy</title>
  @include('partials.public-head')
</head>

<body class="mr-theme">

  @include('partials.public-nav')

  <div class="mr-page-header">
    <div class="container">
      <h1>Privacy Policy</h1>
    </div>
  </div>

  <div class="mr-content">
    <div class="container">
      <div style="max-width: 800px; margin: 0 auto;">

        <h2>Introduction</h2>
        <p>Welcome to the Martian Congressional Republic, an innovative  decentralized blockchain-based governance system and its reference implementation. By visiting, accessing, or using our services, you consent to the policies and practices described in this Privacy Policy, so please review them thoroughly. Should you find any policies or practices described here unacceptable, please refrain from using our services. References to "we", "us", or "our" in this Privacy Policy refer to the Marscoin Foundation, Inc. (Non-Profit) and any of its affiliates.</p>

        <h2>General Terms</h2>
        <p>This Privacy Policy outlines the types of information we collect, the reasons for collecting it, and how we handle your information. Your privacy is important to us, so whether you are new to the Martian Congressional Republic or a long-time participant, please take the time to get to know our practices. We encourage you to keep a copy of this Privacy Policy, but note that we may modify these policies at any time. You can always find the latest version here on this page. Continued use of our services after changes means you accept those changes. If you do not agree to this Privacy Policy, please do not use our services..</p>

        <h2>Open Source Participation</h2>
        <p>The entire Martian Congressional Republic project, including all associated tools and the technology stack, is hosted publicly on GitHub at github.com/marscoin/martianrepublic. All code is available under the MIT License, which permits free use, including the rights to copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software. We actively encourage and invite the public to engage with our codebase—whether by copying, forking, or spawning derivative works, or by contributing improvements. The Marscoin™ Foundation is enthusiastic about partnerships and collaborative projects that advance the technologies and tools designed to help humanity settle Mars and the broader Solar System. We welcome all who wish to contribute to these efforts and are excited to explore collaborative possibilities that enhance our mission.</p>

        <h2>Digital Assets</h2>
        <p>As used here, "Digital Asset" refers to Marscoin and other blockchain-based assets used within our system, all governed by cryptographic protocols which  are decentralized, and open source. These assets are used as a medium of exchange and store of value within our community.</p>

        <h2>Governance and Voting System</h2>
        <p>The Martian Congressional Republic establishes a pioneering form of governance utilizing an end-to-end encrypted, cryptographically secure, and fully auditable voting system. This system necessitates the establishment of a voter registry that collects minimal Personally Identifiable Information (PII). The collection of this data is crucial for the basic functioning of our governance model and is shared openly with all members of the community. However, it is important to note that the submission of this data is entirely voluntary, as is the level of participation in our system. We gather no additional data beyond what is necessary for participation in the voting process, ensuring that our members maintain control over their personal information and their involvement.</p>

        <h2>Information We Collect</h2>
        <p>
        <ul>
          <li><strong>Device Information</strong>: Information automatically collected about your device, such as hardware, operating system, and browser.</li>
          <li><strong>Location Information</strong>: Information automatically collected via analytics to determine your location, including IP addresses and domain names.</li>
          <li><strong>Log Information</strong>: Information generated by your use of our services automatically collected and stored in our logs.</li>
          <li><strong>Account Information</strong>: Information from your account activities such as transactions and balances.</li>
          <li><strong>Correspondence</strong>: Information you provide in communications with us regarding account management and support.</li>
        </ul>
        </p>

        <h2>Cookies</h2>
        <p>We use cookies and similar tracking technologies on your device to help recognize you as a user, enhance your user experience by customizing our services and content, and ensure your account security by detecting irregular activities. If you block or delete cookies, some features may not be available. If you do not consent to cookies, please do not use our services.</p>

        <h2>Use of Information</h2>
        <p>The information we collect is used to enhance your experience, protect against fraud, and improve our services. We may share information with trusted third-party service providers who assist us in operating our platform. These providers are bound by strict confidentiality obligations.</p>

        <h2>Sharing and Disclosure</h2>
        <p>We do not sell your personal information. We may share your information with law enforcement or regulatory agencies if required. We use your information to provide and improve our services, conduct security and fraud prevention checks, and support customer service.</p>

        <h2>Data Accuracy and Retention</h2>
        <p>We take steps to ensure your information is accurate and retained only as long as necessary for the purposes for which it was collected, unless further retention is required by law.</p>

        <h2>Online Web Wallet</h2>
        <p>Our online web wallet is completely non-custodial, meaning that users have full control over their funds and are solely responsible for managing and securing their private keys or seed phrases. The website does not store any keys unencrypted. Users are strongly encouraged to always back up their keys or seed phrases and keep them in a secure location. It's essential to understand that disclosing your private key or seed phrase to anyone may result in a loss of funds, as it provides access to your cryptocurrency holdings. We cannot recover lost or stolen funds resulting from the unauthorized disclosure of private keys or seed phrases.</p>

        <h2>Access and Correction of Information</h2>
        <p>You have the right to access and correct your information. For requests, please contact us at info@marscoin.org. A fee may apply for data access requests to cover administrative costs.</p>

        <h2>Questions</h2>
        <p>If you have questions or concerns about our privacy practices, please contact us at info@marscoin.org.</p>

        <p>By using the Martian Congressional Republic services, you acknowledge and agree to this Privacy Policy.</p>

      </div>
    </div>
  </div>

  @include('partials.public-footer')

  <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
</body>
</html>
