name: Test Coverage & Analysis

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: pcov
        
    - name: Install Dependencies
      run: composer install

    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --memory-limit=2G
      
    - name: Run Tests with Coverage
      run: ./vendor/bin/pest --coverage --exclude-group wip --coverage-clover=coverage.xml
      
    - name: Upload Coverage Reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true