name: Test Coverage & Analysis

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: xdebug
  
  
    - name: Install Dependencies
      run: |
        cp composer_action.json composer.json
        composer install
        
    - name: Run PHPStan
      run: ./vendor/bin/phpstan analyse --memory-limit=2G
      
    - name: Run Tests with Coverage
          run: ./vendor/bin/pest --coverage --exclude-group wip --coverage-clover=clover.xml
          
    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      uses: coverallsapp/github-action@v2
      with:
        format: clover
        file: clover.xml